### ISSUE TITLE
SQLServer数据库

### ISSUE THREAD

**Issue by hxp0618** [somenzz/database-sync#3]
请问这个支持SQLServer数据库与其他数据库的表结构同步吗

**Comment by somenzz** [comment]
这个使用的是 JDBC，只要有相应的 JDBC 驱动就可以，自己在做下不同数据库建表语句的适配即可，我自己只测试了 db2、mysql、oracle、postgresql。

**Comment by somenzz** [comment]
已经加入了 SQLServer 的数据库驱动
